# Generated by Django 5.0.2 on 2024-02-28 16:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0002_rename_customer_edituer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edituer',
            new_name='Customer',
        ),
    ]
