# Generated by Django 5.0.2 on 2024-03-08 15:36

import takouine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0007_stagiaire_avatar_stagiaire_date_début_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(default=takouine.models.generate_stagiaire_code, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='formation',
            field=models.CharField(choices=[('Francais', 'Francais'), ('Español', 'Español'), ('Allemand', 'Allemand'), ('English', 'English')], max_length=200, null=True),
        ),
    ]
