# Generated by Django 5.0.2 on 2024-03-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0008_stagiaire_stagiairecode_alter_stagiaire_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='formation',
            field=models.CharField(choices=[('English', 'English'), ('Francais', 'Francais'), ('Español', 'Español'), ('Allemand', 'Allemand')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(default='KT319c2c5d', max_length=100, null=True),
        ),
    ]
