# Generated by Django 5.0.2 on 2024-03-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0011_alter_stagiaire_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='Achat',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='Visite',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='formation',
            field=models.CharField(choices=[('Allemand', 'Allemand'), ('Español', 'Español'), ('Francais', 'Francais'), ('English', 'English')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(default='KT9755c356', max_length=100, null=True),
        ),
    ]
