# Generated by Django 5.0.2 on 2024-03-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0013_alter_partenaire_achat_alter_partenaire_visite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='formation',
            field=models.CharField(choices=[('Francais', 'Francais'), ('Español', 'Español'), ('English', 'English'), ('Allemand', 'Allemand')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(default='KT36bdacc8', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takouine.partenaire')),
            ],
        ),
    ]
