# Generated by Django 5.0.2 on 2024-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0015_remove_partenaire_achat_alter_stagiaire_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='Achat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='formation',
            field=models.CharField(choices=[('Español', 'Español'), ('Allemand', 'Allemand'), ('English', 'English'), ('Francais', 'Francais')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(default='KT5a47b4f0', max_length=100, null=True),
        ),
    ]
