# Generated by Django 5.0.2 on 2024-03-11 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0017_alter_stagiaire_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='stagiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='takouine.stagiaire'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='formation',
            field=models.CharField(choices=[('Francais', 'Francais'), ('English', 'English'), ('Español', 'Español'), ('Allemand', 'Allemand')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(default='KT54d0dee5', max_length=100, null=True),
        ),
    ]
