# Generated by Django 5.0.2 on 2024-03-11 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0018_achat_stagiaire_alter_stagiaire_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='stagiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='takouine.stagiaire'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(default='KTf608e587', max_length=100, null=True),
        ),
    ]
