# Generated by Django 5.0.2 on 2024-03-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0021_alter_stagiaire_formation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='formation',
            field=models.CharField(choices=[('English', 'English'), ('Allemand', 'Allemand'), ('Español', 'Español'), ('Francais', 'Francais')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(default='KT77c8e7ab', max_length=100, null=True),
        ),
    ]
