# Generated by Django 5.0.2 on 2024-03-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0032_alter_achat_date_added_alter_stagiaire_formation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='formation',
            field=models.CharField(choices=[('Francais', 'Francais'), ('Allemand', 'Allemand'), ('Español', 'Español'), ('English', 'English')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(default='KTe7e21054', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visite',
            name='date_visited',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
