# Generated by Django 5.0.2 on 2024-03-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0033_alter_achat_date_added_alter_stagiaire_formation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='formation',
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(default='KT03d48d21', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='formations',
            field=models.ManyToManyField(to='takouine.formation'),
        ),
    ]
