# Generated by Django 5.0.2 on 2024-03-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0034_formation_remove_stagiaire_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(default='KTf5f19858', max_length=100, null=True),
        ),
    ]
