# Generated by Django 5.0.2 on 2024-03-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0037_partenaire_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='Companyfield',
        ),
    ]
