# Generated by Django 5.0.2 on 2024-03-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0040_remove_partenaire_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='Companyemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
