# Generated by Django 5.0.2 on 2024-03-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0042_partenaire_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='CompanyName',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
