# Generated by Django 5.0.2 on 2024-04-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0046_rename_slug_partenaire_slugpartenaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edituer',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
