# Generated by Django 5.0.2 on 2024-04-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0048_edituer_slugedituer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edituer',
            name='slugEdituer',
        ),
    ]
