# Generated by Django 5.0.2 on 2024-04-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0050_edituer_slugedituer'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='slugFormation',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
