# Generated by Django 5.0.7 on 2024-07-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0052_alter_formation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='discount',
            field=models.CharField(blank=True, choices=[('Entre 5% et 15%', 'Entre 5% et 15%'), ('Entre 15% et 25%', 'Entre 15% et 25%'), ('Entre 25% et 50%', 'Entre 25% et 50%'), ('Plus que 50%', 'Plus que 50%')], max_length=50, null=True),
        ),
    ]
