# Generated by Django 5.0.7 on 2024-07-31 14:17

import takouine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takouine', '0053_partenaire_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='formations',
            field=models.ManyToManyField(blank=True, to='takouine.formation'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stagiaireCode',
            field=models.CharField(blank=True, default=takouine.models.generate_stagiaire_code, max_length=100, null=True),
        ),
    ]
